// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class AffiliatesResource extends BaseResource {
  async list(params?: paths['/affiliates']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/affiliates', { params: { query: params } }));
  }

  async get(affiliateId: string) {
    return this.unwrap(this.api.GET('/affiliates/{id}', { params: { path: { id: affiliateId } } }));
  }
}
