// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class AffiliateCommissionsResource extends BaseResource {
  async list(params?: paths['/affiliate_commissions']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/affiliate_commissions', { params: { query: params } }));
  }

  async get(commissionId: string) {
    return this.unwrap(this.api.GET('/affiliate_commissions/{id}', { params: { path: { id: commissionId } } }));
  }
}
