// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class AffiliateProgramsResource extends BaseResource {
  async list(params?: paths['/affiliate_programs']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/affiliate_programs', { params: { query: params } }));
  }

  async get(programId: string) {
    return this.unwrap(this.api.GET('/affiliate_programs/{id}', { params: { path: { id: programId } } }));
  }
}
