// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class AffiliatePayoutsResource extends BaseResource {
  async list(params?: paths['/affiliate_payouts']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/affiliate_payouts', { params: { query: params } }));
  }

  async get(payoutId: string) {
    return this.unwrap(this.api.GET('/affiliate_payouts/{id}', { params: { path: { id: payoutId } } }));
  }
}
