// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class AffiliateReferralsResource extends BaseResource {
  async list(params?: paths['/affiliate_referrals']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/affiliate_referrals', { params: { query: params } }));
  }

  async get(referralId: string) {
    return this.unwrap(this.api.GET('/affiliate_referrals/{id}', { params: { path: { id: referralId } } }));
  }
}
