// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class AgentsResource extends BaseResource {
  async list(params?: paths['/agents']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/agents', { params: { query: params } }));
  }

  async findOrCreate(data: NonNullable<paths['/agents']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/agents', { body: data }));
  }
}
