// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths, components } from '../generated/api';

export class AiAgentRunsResource extends BaseResource {
  async create(agentId: string, data: NonNullable<paths['/ai/agents/{agentId}/runs']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/ai/agents/{agentId}/runs', { params: { path: { agentId } }, body: data }));
  }

  async get(agentId: string, runId: string) {
    return this.unwrap(this.api.GET('/ai/agents/{agentId}/runs/{runId}', { params: { path: { agentId, runId } } }));
  }
  /**
   * Create an agent run and poll until it reaches a terminal status.
   */
  async createAndWait(
    agentId: string,
    data?: paths['/ai/agents/{agentId}/runs']['post']['requestBody']['content']['application/json'],
    options?: { timeout?: number; pollInterval?: number },
  ): Promise<components['schemas']['AgentRun']> {
    const { timeout = 300_000, pollInterval = 2_000 } = options ?? {};
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const result = await this.create(agentId, data as any);
    const run = (result as { run: components['schemas']['AgentRun'] }).run;
    if (!run?.id) throw new Error('Agent run ID not returned');
    const start = Date.now();
    while (Date.now() - start < timeout) {
      const response = await this.get(agentId, run.id);
      const agentRun = (response as { run: components['schemas']['AgentRun'] }).run;
      if (agentRun.status === 'completed' || agentRun.status === 'error') return agentRun;
      await new Promise(resolve => setTimeout(resolve, pollInterval));
    }
    throw new Error(`Agent run timed out after ${timeout}ms`);
  }
}
