// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class AppsResource extends BaseResource {
  async list(params?: paths['/apps']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/apps', { params: { query: params } }));
  }

  async analyze(appId: string, data: NonNullable<paths['/apps/{id}/analyze']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/apps/{id}/analyze', { params: { path: { id: appId } }, body: data }));
  }

  async get(appId: string) {
    return this.unwrap(this.api.GET('/apps/{id}', { params: { path: { id: appId } } }));
  }

  async getPlan(appId: string, planId: string) {
    return this.unwrap(this.api.GET('/apps/{id}/plans/{planId}', { params: { path: { id: appId, planId } } }));
  }

  async updatePlan(appId: string, planId: string, data: NonNullable<paths['/apps/{id}/plans/{planId}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/apps/{id}/plans/{planId}', { params: { path: { id: appId, planId } }, body: data }));
  }

  async getAppEvent(appId: string, appEventId: string) {
    return this.unwrap(this.api.GET('/apps/{id}/app_events/{appEventId}', { params: { path: { id: appId, appEventId } } }));
  }

  async listAppEvents(appId: string, params?: paths['/apps/{id}/app_events']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/apps/{id}/app_events', { params: { path: { id: appId }, query: params } }));
  }

  async createAppEvent(appId: string, data: NonNullable<paths['/apps/{id}/app_events']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/apps/{id}/app_events', { params: { path: { id: appId } }, body: data }));
  }

  async getChecklist(appId: string, checklistId: string) {
    return this.unwrap(this.api.GET('/apps/{appId}/checklists/{checklistId}', { params: { path: { appId, checklistId } } }));
  }

  async updateChecklist(appId: string, checklistId: string, data: NonNullable<paths['/apps/{appId}/checklists/{checklistId}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/apps/{appId}/checklists/{checklistId}', { params: { path: { appId, checklistId } }, body: data }));
  }

  async deleteChecklist(appId: string, checklistId: string) {
    return this.unwrap(this.api.DELETE('/apps/{appId}/checklists/{checklistId}', { params: { path: { appId, checklistId } } }));
  }

  async listChecklists(appId: string) {
    return this.unwrap(this.api.GET('/apps/{appId}/checklists', { params: { path: { appId } } }));
  }

  async createChecklist(appId: string, data: NonNullable<paths['/apps/{appId}/checklists']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/apps/{appId}/checklists', { params: { path: { appId } }, body: data }));
  }

  async archivePlan(appId: string, planId: string) {
    return this.unwrap(this.api.PUT('/apps/{id}/plans/{planId}/archive', { params: { path: { id: appId, planId } } }));
  }

  async unarchivePlan(appId: string, planId: string) {
    return this.unwrap(this.api.PUT('/apps/{id}/plans/{planId}/unarchive', { params: { path: { id: appId, planId } } }));
  }

  async getFeature(appId: string, featureId: string) {
    return this.unwrap(this.api.GET('/apps/{appId}/plans/features/{featureId}', { params: { path: { appId, featureId } } }));
  }

  async updateFeature(appId: string, featureId: string, data: NonNullable<paths['/apps/{appId}/plans/features/{featureId}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/apps/{appId}/plans/features/{featureId}', { params: { path: { appId, featureId } }, body: data }));
  }

  async deleteFeature(appId: string, featureId: string) {
    return this.unwrap(this.api.DELETE('/apps/{appId}/plans/features/{featureId}', { params: { path: { appId, featureId } } }));
  }

  async listFeatures(appId: string) {
    return this.unwrap(this.api.GET('/apps/{appId}/plans/features', { params: { path: { appId } } }));
  }

  async createFeature(appId: string, data: NonNullable<paths['/apps/{appId}/plans/features']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/apps/{appId}/plans/features', { params: { path: { appId } }, body: data }));
  }

  async listPlans(appId: string, params?: paths['/apps/{id}/plans']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/apps/{id}/plans', { params: { path: { id: appId }, query: params } }));
  }

  async createPlan(appId: string, data: NonNullable<paths['/apps/{id}/plans']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/apps/{id}/plans', { params: { path: { id: appId } }, body: data }));
  }

  async getReview(appId: string, reviewId: string) {
    return this.unwrap(this.api.GET('/apps/{id}/reviews/{reviewId}', { params: { path: { id: appId, reviewId } } }));
  }

  async listReviews(appId: string, params?: paths['/apps/{id}/reviews']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/apps/{id}/reviews', { params: { path: { id: appId }, query: params } }));
  }

  async getSkill(appId: string, skillId: string, params?: paths['/apps/{id}/skills/{skillId}']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/apps/{id}/skills/{skillId}', { params: { path: { id: appId, skillId }, query: params } }));
  }

  async createSkill(appId: string, skillId: string, data: NonNullable<paths['/apps/{id}/skills/{skillId}']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/apps/{id}/skills/{skillId}', { params: { path: { id: appId, skillId } }, body: data }));
  }

  async getUsageMetric(appId: string, usageMetricId: string) {
    return this.unwrap(this.api.GET('/apps/{id}/usage_metrics/{usageMetricId}', { params: { path: { id: appId, usageMetricId } } }));
  }

  async updateUsageMetric(appId: string, usageMetricId: string, data: NonNullable<paths['/apps/{id}/usage_metrics/{usageMetricId}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/apps/{id}/usage_metrics/{usageMetricId}', { params: { path: { id: appId, usageMetricId } }, body: data }));
  }

  async deleteUsageMetric(appId: string, usageMetricId: string) {
    return this.unwrap(this.api.DELETE('/apps/{id}/usage_metrics/{usageMetricId}', { params: { path: { id: appId, usageMetricId } } }));
  }

  async listUsageMetrics(appId: string) {
    return this.unwrap(this.api.GET('/apps/{id}/usage_metrics', { params: { path: { id: appId } } }));
  }

  async createUsageMetric(appId: string, data: NonNullable<paths['/apps/{id}/usage_metrics']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/apps/{id}/usage_metrics', { params: { path: { id: appId } }, body: data }));
  }
}
