// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';

export class AssistantResource extends BaseResource {
  async getConversation(conversationId: string) {
    return this.unwrap(this.api.GET('/assistant/conversations/{id}', { params: { path: { id: conversationId } } }));
  }
}
