// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class AttachmentsResource extends BaseResource {
  async create(data: NonNullable<paths['/attachments']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/attachments', { body: data }));
  }
  async upload(
    file: {
      uri?: string;
      blob?: Blob;
      name: string;
      contentType: string;
      sizeBytes?: number;
    },
  ): Promise<{
    url: string;
    name: string;
    contentType: string;
    sizeBytes: number;
  }> {
    if (!file.uri && !file.blob) {
      throw new Error('AttachmentsResource.upload: either `uri` or `blob` is required');
    }
    const blob = file.blob ?? (await (await fetch(file.uri!)).blob());
    const created = await this.create({
      filename: file.name,
      contentType: file.contentType,
    });
    const putRes = await fetch(created.signedUrl, {
      method: 'PUT',
      headers: { 'Content-Type': file.contentType },
      body: blob,
    });
    if (!putRes.ok) {
      throw new Error(
        `AttachmentsResource.upload: PUT to signed URL failed with status ${putRes.status}`,
      );
    }
    return {
      url: created.downloadUrl,
      name: file.name,
      contentType: file.contentType,
      sizeBytes: file.sizeBytes ?? blob.size,
    };
  }
}
