// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class ChannelsResource extends BaseResource {
  async list(params?: paths['/channels']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/channels', { params: { query: params } }));
  }

  async create(data: NonNullable<paths['/channels']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/channels', { body: data }));
  }
}
