// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class ChargesResource extends BaseResource {
  async list(params?: paths['/charges']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/charges', { params: { query: params } }));
  }
}
