// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class CompaniesResource extends BaseResource {
  async list(params?: paths['/companies']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/companies', { params: { query: params } }));
  }

  async create(data: NonNullable<paths['/companies']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/companies', { body: data }));
  }

  async get(companyId: string) {
    return this.unwrap(this.api.GET('/companies/{id}', { params: { path: { id: companyId } } }));
  }

  async update(companyId: string, data: NonNullable<paths['/companies/{id}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/companies/{id}', { params: { path: { id: companyId } }, body: data }));
  }

  async del(companyId: string) {
    return this.unwrap(this.api.DELETE('/companies/{id}', { params: { path: { id: companyId } } }));
  }
}
