// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class CustomerSegmentsResource extends BaseResource {
  async list(params?: paths['/customer_segments']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/customer_segments', { params: { query: params } }));
  }

  async get(segmentId: string) {
    return this.unwrap(this.api.GET('/customer_segments/{id}', { params: { path: { id: segmentId } } }));
  }
}
