// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class DealActivitiesResource extends BaseResource {
  async list(params?: paths['/deal_activities']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/deal_activities', { params: { query: params } }));
  }

  async create(data: NonNullable<paths['/deal_activities']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/deal_activities', { body: data }));
  }

  async get(activityId: string) {
    return this.unwrap(this.api.GET('/deal_activities/{id}', { params: { path: { id: activityId } } }));
  }

  async update(activityId: string, data: NonNullable<paths['/deal_activities/{id}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/deal_activities/{id}', { params: { path: { id: activityId } }, body: data }));
  }

  async del(activityId: string) {
    return this.unwrap(this.api.DELETE('/deal_activities/{id}', { params: { path: { id: activityId } } }));
  }
}
