// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class DealsResource extends BaseResource {
  async list(params?: paths['/deals']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/deals', { params: { query: params } }));
  }

  async create(data: NonNullable<paths['/deals']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/deals', { body: data }));
  }

  async listEvents(dealId: string, params?: paths['/deals/{id}/events']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/deals/{id}/events', { params: { path: { id: dealId }, query: params } }));
  }

  async createEvent(dealId: string, data: NonNullable<paths['/deals/{id}/events']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/deals/{id}/events', { params: { path: { id: dealId } }, body: data }));
  }

  async get(dealId: string) {
    return this.unwrap(this.api.GET('/deals/{id}', { params: { path: { id: dealId } } }));
  }

  async update(dealId: string, data: NonNullable<paths['/deals/{id}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/deals/{id}', { params: { path: { id: dealId } }, body: data }));
  }

  async del(dealId: string) {
    return this.unwrap(this.api.DELETE('/deals/{id}', { params: { path: { id: dealId } } }));
  }

  async getTimeline(dealId: string, params?: paths['/deals/{id}/timeline']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/deals/{id}/timeline', { params: { path: { id: dealId }, query: params } }));
  }
}
