// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class DevicesResource extends BaseResource {
  async create(data: NonNullable<paths['/devices']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/devices', { body: data }));
  }
}
