// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class DocsResource extends BaseResource {
  async getTree(params: paths['/docs/tree']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/docs/tree', { params: { query: params } }));
  }

  async listCollections(params: paths['/docs/collections']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/docs/collections', { params: { query: params } }));
  }

  async createCollection(data: NonNullable<paths['/docs/collections']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/docs/collections', { body: data }));
  }

  async listGroups(params: paths['/docs/groups']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/docs/groups', { params: { query: params } }));
  }

  async createGroup(data: NonNullable<paths['/docs/groups']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/docs/groups', { body: data }));
  }

  async generatePage(data: NonNullable<paths['/docs/pages/generate']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/docs/pages/generate', { body: data }));
  }

  async listPages(params?: paths['/docs/pages']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/docs/pages', { params: { query: params } }));
  }

  async createPage(data: NonNullable<paths['/docs/pages']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/docs/pages', { body: data }));
  }

  async listRepositoriesGet(params?: paths['/docs/repositories']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/docs/repositories', { params: { query: params } }));
  }

  async listSites(params?: paths['/docs/sites']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/docs/sites', { params: { query: params } }));
  }

  async createSite(data: NonNullable<paths['/docs/sites']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/docs/sites', { body: data }));
  }

  async archivePage(pageId: string) {
    return this.unwrap(this.api.POST('/docs/pages/{page_id}/archive', { params: { path: { page_id: pageId } } }));
  }

  async unarchivePage(pageId: string) {
    return this.unwrap(this.api.DELETE('/docs/pages/{page_id}/archive', { params: { path: { page_id: pageId } } }));
  }

  async getPage(pageId: string, params?: paths['/docs/pages/{page_id}']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/docs/pages/{page_id}', { params: { path: { page_id: pageId }, query: params } }));
  }

  async updatePage(pageId: string, data: NonNullable<paths['/docs/pages/{page_id}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/docs/pages/{page_id}', { params: { path: { page_id: pageId } }, body: data }));
  }

  async deletePage(pageId: string) {
    return this.unwrap(this.api.DELETE('/docs/pages/{page_id}', { params: { path: { page_id: pageId } } }));
  }

  async publishPage(pageId: string, data: NonNullable<paths['/docs/pages/{page_id}/publish']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/docs/pages/{page_id}/publish', { params: { path: { page_id: pageId } }, body: data }));
  }

  async unpublishPage(pageId: string) {
    return this.unwrap(this.api.DELETE('/docs/pages/{page_id}/publish', { params: { path: { page_id: pageId } } }));
  }

  async getSite(docId: string, params?: paths['/docs/sites/{id}']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/docs/sites/{id}', { params: { path: { id: docId }, query: params } }));
  }

  async updateSite(docId: string, data: NonNullable<paths['/docs/sites/{id}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/docs/sites/{id}', { params: { path: { id: docId } }, body: data }));
  }

  async deleteSite(docId: string) {
    return this.unwrap(this.api.DELETE('/docs/sites/{id}', { params: { path: { id: docId } } }));
  }

  async createRepository(docId: string, data: NonNullable<paths['/docs/sites/{id}/repositories']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/docs/sites/{id}/repositories', { params: { path: { id: docId } }, body: data }));
  }

  async updateRepositoryPut(docId: string, data: NonNullable<paths['/docs/sites/{id}/repositories']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/docs/sites/{id}/repositories', { params: { path: { id: docId } }, body: data }));
  }

  async deleteRepositories(docId: string, data: NonNullable<paths['/docs/sites/{id}/repositories']['delete']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.DELETE('/docs/sites/{id}/repositories', { params: { path: { id: docId } }, body: data }));
  }

  async updateRedirectPut(docId: string, redirectId: string, data: NonNullable<paths['/docs/repositories/{id}/redirects/{redirect_id}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/docs/repositories/{id}/redirects/{redirect_id}', { params: { path: { id: docId, redirect_id: redirectId } }, body: data }));
  }

  async deleteRedirectDelete(docId: string, redirectId: string) {
    return this.unwrap(this.api.DELETE('/docs/repositories/{id}/redirects/{redirect_id}', { params: { path: { id: docId, redirect_id: redirectId } } }));
  }

  async listRedirectsGet(docId: string) {
    return this.unwrap(this.api.GET('/docs/repositories/{id}/redirects', { params: { path: { id: docId } } }));
  }

  async createRedirectPost(docId: string, data: NonNullable<paths['/docs/repositories/{id}/redirects']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/docs/repositories/{id}/redirects', { params: { path: { id: docId } }, body: data }));
  }

  async updateCollection(collectionId: string, data: NonNullable<paths['/docs/collections/{collection_id}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/docs/collections/{collection_id}', { params: { path: { collection_id: collectionId } }, body: data }));
  }

  async deleteCollection(collectionId: string) {
    return this.unwrap(this.api.DELETE('/docs/collections/{collection_id}', { params: { path: { collection_id: collectionId } } }));
  }

  async updateGroup(groupId: string, data: NonNullable<paths['/docs/groups/{group_id}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/docs/groups/{group_id}', { params: { path: { group_id: groupId } }, body: data }));
  }

  async deleteGroup(groupId: string) {
    return this.unwrap(this.api.DELETE('/docs/groups/{group_id}', { params: { path: { group_id: groupId } } }));
  }

  async getStatus(jobKey: string) {
    return this.unwrap(this.api.GET('/docs/pages/generate/status/{jobKey}', { params: { path: { jobKey } } }));
  }

  async getRepository(docId: string, params?: paths['/docs/repositories/{id}']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/docs/repositories/{id}', { params: { path: { id: docId }, query: params } }));
  }
  async regeneratePage(pageId: string, data: NonNullable<paths['/docs/pages/{page_id}/generate']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/docs/pages/{page_id}/generate', { params: { path: { page_id: pageId } }, body: data }));
  }
}
