// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class EmailDeliveriesResource extends BaseResource {
  async list(params?: paths['/email/deliveries']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/email/deliveries', { params: { query: params } }));
  }

  async get(deliveryId: string) {
    return this.unwrap(this.api.GET('/email/deliveries/{id}', { params: { path: { id: deliveryId } } }));
  }
}
