// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class EmailSendersResource extends BaseResource {
  async list(params?: paths['/email/senders']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/email/senders', { params: { query: params } }));
  }
}
