// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class EmailLayoutsResource extends BaseResource {
  async list(params?: paths['/email/layouts']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/email/layouts', { params: { query: params } }));
  }
}
