// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class EmailCampaignsResource extends BaseResource {
  async list(params?: paths['/email/campaigns']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/email/campaigns', { params: { query: params } }));
  }

  async create(data: NonNullable<paths['/email/campaigns']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/email/campaigns', { body: data }));
  }

  async cancel(campaignId: string) {
    return this.unwrap(this.api.POST('/email/campaigns/{id}/cancel', { params: { path: { id: campaignId } } }));
  }

  async deliver(campaignId: string, data: NonNullable<paths['/email/campaigns/{id}/deliver']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/email/campaigns/{id}/deliver', { params: { path: { id: campaignId } }, body: data }));
  }

  async preview(campaignId: string, params?: paths['/email/campaigns/{id}/preview']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/email/campaigns/{id}/preview', { params: { path: { id: campaignId }, query: params } }));
  }

  async send(campaignId: string, data: NonNullable<paths['/email/campaigns/{id}/send']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/email/campaigns/{id}/send', { params: { path: { id: campaignId } }, body: data }));
  }

  async test(campaignId: string, data: NonNullable<paths['/email/campaigns/{id}/test']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/email/campaigns/{id}/test', { params: { path: { id: campaignId } }, body: data }));
  }

  async get(campaignId: string) {
    return this.unwrap(this.api.GET('/email/campaigns/{id}', { params: { path: { id: campaignId } } }));
  }

  async update(campaignId: string, data: NonNullable<paths['/email/campaigns/{id}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/email/campaigns/{id}', { params: { path: { id: campaignId } }, body: data }));
  }

  async del(campaignId: string) {
    return this.unwrap(this.api.DELETE('/email/campaigns/{id}', { params: { path: { id: campaignId } } }));
  }
}
