// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class EmailUnsubscribeGroupsResource extends BaseResource {
  async list() {
    return this.unwrap(this.api.GET('/email/unsubscribe_groups'));
  }

  async deleteMemberDelete(groupId: string, memberId: string) {
    return this.unwrap(this.api.DELETE('/email/unsubscribe_groups/{id}/members/{member_id}', { params: { path: { id: groupId, member_id: memberId } } }));
  }

  async listMembers(groupId: string) {
    return this.unwrap(this.api.GET('/email/unsubscribe_groups/{id}/members', { params: { path: { id: groupId } } }));
  }

  async createMember(groupId: string, data: NonNullable<paths['/email/unsubscribe_groups/{id}/members']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/email/unsubscribe_groups/{id}/members', { params: { path: { id: groupId } }, body: data }));
  }
}
