// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class EntitiesResource extends BaseResource {
  async search(params?: paths['/entities']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/entities', { params: { query: params } }));
  }
}
