// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class FlowsResource extends BaseResource {
  async list(params?: paths['/flows']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/flows', { params: { query: params } }));
  }

  async create(data: NonNullable<paths['/flows']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/flows', { body: data }));
  }

  async get(flowId: string) {
    return this.unwrap(this.api.GET('/flows/{id}', { params: { path: { id: flowId } } }));
  }

  async update(flowId: string, data: NonNullable<paths['/flows/{id}']['patch']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PATCH('/flows/{id}', { params: { path: { id: flowId } }, body: data }));
  }

  async del(flowId: string) {
    return this.unwrap(this.api.DELETE('/flows/{id}', { params: { path: { id: flowId } } }));
  }
}
