// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class FlowExtensionsResource extends BaseResource {
  async listActions() {
    return this.unwrap(this.api.GET('/flow/extensions/actions'));
  }

  async createAction(data: NonNullable<paths['/flow/extensions/actions']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/flow/extensions/actions', { body: data }));
  }

  async listTriggers() {
    return this.unwrap(this.api.GET('/flow/extensions/triggers'));
  }

  async createTriggerPost(data: NonNullable<paths['/flow/extensions/triggers']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/flow/extensions/triggers', { body: data }));
  }

  async validateSchema(data: NonNullable<paths['/flow/extensions/triggers/validate-schema']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/flow/extensions/triggers/validate-schema', { body: data }));
  }

  async updateRun(extensionId: string, data: NonNullable<paths['/flow/actions/runs/{id}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/flow/actions/runs/{id}', { params: { path: { id: extensionId } }, body: data }));
  }

  async fireTrigger(handle: string, data: NonNullable<paths['/flow/extensions/triggers/{handle}/fire']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/flow/extensions/triggers/{handle}/fire', { params: { path: { handle } }, body: data }));
  }

  async updateAction(extensionId: string, data: NonNullable<paths['/flow/extensions/actions/{id}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/flow/extensions/actions/{id}', { params: { path: { id: extensionId } }, body: data }));
  }

  async deleteAction(extensionId: string) {
    return this.unwrap(this.api.DELETE('/flow/extensions/actions/{id}', { params: { path: { id: extensionId } } }));
  }

  async getTrigger(handle: string) {
    return this.unwrap(this.api.GET('/flow/extensions/triggers/{handle}', { params: { path: { handle } } }));
  }

  async replaceTrigger(handle: string, data: NonNullable<paths['/flow/extensions/triggers/{handle}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/flow/extensions/triggers/{handle}', { params: { path: { handle } }, body: data }));
  }

  async updateTrigger(handle: string, data: NonNullable<paths['/flow/extensions/triggers/{handle}']['patch']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PATCH('/flow/extensions/triggers/{handle}', { params: { path: { handle } }, body: data }));
  }

  async deleteTrigger(handle: string) {
    return this.unwrap(this.api.DELETE('/flow/extensions/triggers/{handle}', { params: { path: { handle } } }));
  }
}
