// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class JournalEntriesResource extends BaseResource {
  async list(params?: paths['/journal_entries']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/journal_entries', { params: { query: params } }));
  }

  async create(data: NonNullable<paths['/journal_entries']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/journal_entries', { body: data }));
  }

  async get(entryId: string, params?: paths['/journal_entries/{id}']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/journal_entries/{id}', { params: { path: { id: entryId }, query: params } }));
  }

  async update(entryId: string, data: NonNullable<paths['/journal_entries/{id}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/journal_entries/{id}', { params: { path: { id: entryId } }, body: data }));
  }

  async del(entryId: string) {
    return this.unwrap(this.api.DELETE('/journal_entries/{id}', { params: { path: { id: entryId } } }));
  }
}
