// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class ListsResource extends BaseResource {
  async list(params?: paths['/lists']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/lists', { params: { query: params } }));
  }

  async create(data: NonNullable<paths['/lists']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/lists', { body: data }));
  }

  async add(listId: string, data: NonNullable<paths['/lists/{id}/add']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/lists/{id}/add', { params: { path: { id: listId } }, body: data }));
  }

  async get(listId: string, params?: paths['/lists/{id}']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/lists/{id}', { params: { path: { id: listId }, query: params } }));
  }

  async update(listId: string, data: NonNullable<paths['/lists/{id}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/lists/{id}', { params: { path: { id: listId } }, body: data }));
  }

  async del(listId: string) {
    return this.unwrap(this.api.DELETE('/lists/{id}', { params: { path: { id: listId } } }));
  }

  async remove(listId: string, data: NonNullable<paths['/lists/{id}/remove']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/lists/{id}/remove', { params: { path: { id: listId } }, body: data }));
  }
}
