// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class MeetingsResource extends BaseResource {
  async list(params?: paths['/meetings']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/meetings', { params: { query: params } }));
  }

  async create(data: NonNullable<paths['/meetings']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/meetings', { body: data }));
  }

  async listPermissions(meetingId: string) {
    return this.unwrap(this.api.GET('/meetings/{id}/permissions', { params: { path: { id: meetingId } } }));
  }

  async createPermission(meetingId: string, data: NonNullable<paths['/meetings/{id}/permissions']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/meetings/{id}/permissions', { params: { path: { id: meetingId } }, body: data }));
  }

  async deletePermissions(meetingId: string, data: NonNullable<paths['/meetings/{id}/permissions']['delete']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.DELETE('/meetings/{id}/permissions', { params: { path: { id: meetingId } }, body: data }));
  }

  async getRecordingUrl(meetingId: string) {
    return this.unwrap(this.api.GET('/meetings/{id}/recording-url', { params: { path: { id: meetingId } } }));
  }

  async acceptTaskSuggestion(meetingId: string, suggestionId: string, data: NonNullable<paths['/meetings/{id}/task-suggestions/{suggestionId}/accept']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/meetings/{id}/task-suggestions/{suggestionId}/accept', { params: { path: { id: meetingId, suggestionId } }, body: data }));
  }

  async dismissTaskSuggestion(meetingId: string, suggestionId: string) {
    return this.unwrap(this.api.POST('/meetings/{id}/task-suggestions/{suggestionId}/dismiss', { params: { path: { id: meetingId, suggestionId } } }));
  }

  async updateVisibility(meetingId: string, data: NonNullable<paths['/meetings/{id}/visibility']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/meetings/{id}/visibility', { params: { path: { id: meetingId } }, body: data }));
  }

  async updateAttendee(meetingId: string, attendeeId: string, data: NonNullable<paths['/meetings/{id}/attendees/{attendeeId}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/meetings/{id}/attendees/{attendeeId}', { params: { path: { id: meetingId, attendeeId } }, body: data }));
  }

  async getTranscription(meetingId: string) {
    return this.unwrap(this.api.GET('/meetings/{id}/transcribe', { params: { path: { id: meetingId } } }));
  }

  async transcribe(meetingId: string, data: NonNullable<paths['/meetings/{id}/transcribe']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/meetings/{id}/transcribe', { params: { path: { id: meetingId } }, body: data }));
  }

  async transcribeUpload(meetingId: string, data?: NonNullable<paths['/meetings/{id}/transcribe/upload']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/meetings/{id}/transcribe/upload', { params: { path: { id: meetingId } }, body: data }));
  }

  async get(meetingId: string) {
    return this.unwrap(this.api.GET('/meetings/{id}', { params: { path: { id: meetingId } } }));
  }

  async update(meetingId: string, data: NonNullable<paths['/meetings/{id}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/meetings/{id}', { params: { path: { id: meetingId } }, body: data }));
  }

  async del(meetingId: string) {
    return this.unwrap(this.api.DELETE('/meetings/{id}', { params: { path: { id: meetingId } } }));
  }
}
