// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class NotificationPreferencesResource extends BaseResource {
  async get() {
    return this.unwrap(this.api.GET('/notification_preferences'));
  }

  async update(data: NonNullable<paths['/notification_preferences']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/notification_preferences', { body: data }));
  }
}
