// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';

export class OrganizationResource extends BaseResource {
  async list() {
    return this.unwrap(this.api.GET('/organization'));
  }
}
