// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class SubscriptionsResource extends BaseResource {
  async list(params?: paths['/subscriptions']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/subscriptions', { params: { query: params } }));
  }

  async get(subscriptionId: string) {
    return this.unwrap(this.api.GET('/subscriptions/{id}', { params: { path: { id: subscriptionId } } }));
  }
}
