// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class SyncedEmailsResource extends BaseResource {
  async list(params?: paths['/synced_emails']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/synced_emails', { params: { query: params } }));
  }

  async create(data: NonNullable<paths['/synced_emails']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/synced_emails', { body: data }));
  }

  async listMessages(syncedEmailId: string) {
    return this.unwrap(this.api.GET('/synced_emails/{id}/messages', { params: { path: { id: syncedEmailId } } }));
  }

  async createMessage(syncedEmailId: string, data: NonNullable<paths['/synced_emails/{id}/messages']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/synced_emails/{id}/messages', { params: { path: { id: syncedEmailId } }, body: data }));
  }

  async get(syncedEmailId: string) {
    return this.unwrap(this.api.GET('/synced_emails/{id}', { params: { path: { id: syncedEmailId } } }));
  }

  async update(syncedEmailId: string, data: NonNullable<paths['/synced_emails/{id}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/synced_emails/{id}', { params: { path: { id: syncedEmailId } }, body: data }));
  }

  async del(syncedEmailId: string) {
    return this.unwrap(this.api.DELETE('/synced_emails/{id}', { params: { path: { id: syncedEmailId } } }));
  }
}
