// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class TasksResource extends BaseResource {
  async list(params?: paths['/tasks']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/tasks', { params: { query: params } }));
  }

  async create(data: NonNullable<paths['/tasks']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/tasks', { body: data }));
  }

  async get(taskId: string) {
    return this.unwrap(this.api.GET('/tasks/{id}', { params: { path: { id: taskId } } }));
  }

  async update(taskId: string, data: NonNullable<paths['/tasks/{id}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/tasks/{id}', { params: { path: { id: taskId } }, body: data }));
  }

  async del(taskId: string) {
    return this.unwrap(this.api.DELETE('/tasks/{id}', { params: { path: { id: taskId } } }));
  }

  async updateComment(taskId: string, commentId: string, data: NonNullable<paths['/tasks/{id}/comments/{commentId}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/tasks/{id}/comments/{commentId}', { params: { path: { id: taskId, commentId } }, body: data }));
  }

  async deleteComment(taskId: string, commentId: string) {
    return this.unwrap(this.api.DELETE('/tasks/{id}/comments/{commentId}', { params: { path: { id: taskId, commentId } } }));
  }

  async listComments(taskId: string) {
    return this.unwrap(this.api.GET('/tasks/{id}/comments', { params: { path: { id: taskId } } }));
  }

  async createComment(taskId: string, data: NonNullable<paths['/tasks/{id}/comments']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/tasks/{id}/comments', { params: { path: { id: taskId } }, body: data }));
  }

  async getTodoItem(taskId: string, itemId: string) {
    return this.unwrap(this.api.GET('/tasks/{id}/todo-items/{itemId}', { params: { path: { id: taskId, itemId } } }));
  }

  async updateTodoItem(taskId: string, itemId: string, data: NonNullable<paths['/tasks/{id}/todo-items/{itemId}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/tasks/{id}/todo-items/{itemId}', { params: { path: { id: taskId, itemId } }, body: data }));
  }

  async deleteTodoItem(taskId: string, itemId: string) {
    return this.unwrap(this.api.DELETE('/tasks/{id}/todo-items/{itemId}', { params: { path: { id: taskId, itemId } } }));
  }

  async getTodoItems(taskId: string) {
    return this.unwrap(this.api.GET('/tasks/{id}/todo-items', { params: { path: { id: taskId } } }));
  }

  async createTodoItems(taskId: string, data: NonNullable<paths['/tasks/{id}/todo-items']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/tasks/{id}/todo-items', { params: { path: { id: taskId } }, body: data }));
  }
}
