// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class TicketsResource extends BaseResource {
  async list(params?: paths['/tickets']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/tickets', { params: { query: params } }));
  }

  async create(data: NonNullable<paths['/tickets']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/tickets', { body: data }));
  }

  async listSavedFilters() {
    return this.unwrap(this.api.GET('/tickets/saved_filters'));
  }

  async createSavedFilter(data: NonNullable<paths['/tickets/saved_filters']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/tickets/saved_filters', { body: data }));
  }

  async listSavedReplies(params?: paths['/tickets/saved_replies']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/tickets/saved_replies', { params: { query: params } }));
  }

  async createSavedReply(data: NonNullable<paths['/tickets/saved_replies']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/tickets/saved_replies', { body: data }));
  }

  async listEvents(ticketId: string, params?: paths['/tickets/{id}/events']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/tickets/{id}/events', { params: { path: { id: ticketId }, query: params } }));
  }

  async createEvent(ticketId: string, data: NonNullable<paths['/tickets/{id}/events']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/tickets/{id}/events', { params: { path: { id: ticketId } }, body: data }));
  }

  async updateEvent(ticketId: string, data: NonNullable<paths['/tickets/{id}/events']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/tickets/{id}/events', { params: { path: { id: ticketId } }, body: data }));
  }

  async get(ticketId: string) {
    return this.unwrap(this.api.GET('/tickets/{id}', { params: { path: { id: ticketId } } }));
  }

  async update(ticketId: string, data: NonNullable<paths['/tickets/{id}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/tickets/{id}', { params: { path: { id: ticketId } }, body: data }));
  }

  async getLoop(ticketId: string, loopId: string) {
    return this.unwrap(this.api.GET('/tickets/{id}/loops/{loopId}', { params: { path: { id: ticketId, loopId } } }));
  }

  async listLoops(ticketId: string, params?: paths['/tickets/{id}/loops']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/tickets/{id}/loops', { params: { path: { id: ticketId }, query: params } }));
  }

  async getMessage(ticketId: string, messageId: string) {
    return this.unwrap(this.api.GET('/tickets/{id}/messages/{messageId}', { params: { path: { id: ticketId, messageId } } }));
  }

  async listMessages(ticketId: string, params?: paths['/tickets/{id}/messages']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/tickets/{id}/messages', { params: { path: { id: ticketId }, query: params } }));
  }

  async createMessage(ticketId: string, data: NonNullable<paths['/tickets/{id}/messages']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/tickets/{id}/messages', { params: { path: { id: ticketId } }, body: data }));
  }

  async updateMessage(ticketId: string, data: NonNullable<paths['/tickets/{id}/messages']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/tickets/{id}/messages', { params: { path: { id: ticketId } }, body: data }));
  }

  async getSavedFilter(filterId: string) {
    return this.unwrap(this.api.GET('/tickets/saved_filters/{filter_id}', { params: { path: { filter_id: filterId } } }));
  }

  async updateSavedFilter(filterId: string, data: NonNullable<paths['/tickets/saved_filters/{filter_id}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/tickets/saved_filters/{filter_id}', { params: { path: { filter_id: filterId } }, body: data }));
  }

  async deleteSavedFilter(filterId: string) {
    return this.unwrap(this.api.DELETE('/tickets/saved_filters/{filter_id}', { params: { path: { filter_id: filterId } } }));
  }

  async getSavedReply(replyId: string) {
    return this.unwrap(this.api.GET('/tickets/saved_replies/{reply_id}', { params: { path: { reply_id: replyId } } }));
  }

  async updateSavedReply(replyId: string, data: NonNullable<paths['/tickets/saved_replies/{reply_id}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/tickets/saved_replies/{reply_id}', { params: { path: { reply_id: replyId } }, body: data }));
  }

  async deleteSavedReply(replyId: string) {
    return this.unwrap(this.api.DELETE('/tickets/saved_replies/{reply_id}', { params: { path: { reply_id: replyId } } }));
  }
}
