// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class TimelineCommentsResource extends BaseResource {
  async list(params?: paths['/timeline_comments']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/timeline_comments', { params: { query: params } }));
  }

  async create(data: NonNullable<paths['/timeline_comments']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/timeline_comments', { body: data }));
  }

  async get(commentId: string) {
    return this.unwrap(this.api.GET('/timeline_comments/{id}', { params: { path: { id: commentId } } }));
  }

  async update(commentId: string, data: NonNullable<paths['/timeline_comments/{id}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/timeline_comments/{id}', { params: { path: { id: commentId } }, body: data }));
  }

  async del(commentId: string, params?: paths['/timeline_comments/{id}']['delete']['parameters']['query']) {
    return this.unwrap(this.api.DELETE('/timeline_comments/{id}', { params: { path: { id: commentId }, query: params } }));
  }
}
