// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class TransactionsResource extends BaseResource {
  async list(params?: paths['/transactions']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/transactions', { params: { query: params } }));
  }

  async get(transactionId: string) {
    return this.unwrap(this.api.GET('/transactions/{id}', { params: { path: { id: transactionId } } }));
  }
}
