// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class UsageEventsResource extends BaseResource {
  async list(params?: paths['/usage_events']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/usage_events', { params: { query: params } }));
  }

  async create(data: NonNullable<paths['/usage_events']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/usage_events', { body: data }));
  }
}
