// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class UsersResource extends BaseResource {
  async list(params?: paths['/users']['get']['parameters']['query']) {
    return this.unwrap(this.api.GET('/users', { params: { query: params } }));
  }

  async get(userId: string) {
    return this.unwrap(this.api.GET('/users/{id}', { params: { path: { id: userId } } }));
  }
}
