// Auto-generated by scripts/generate.ts — DO NOT EDIT
import { BaseResource } from './base';
import type { paths } from '../generated/api';

export class WebhooksResource extends BaseResource {
  async list() {
    return this.unwrap(this.api.GET('/webhooks'));
  }

  async create(data: NonNullable<paths['/webhooks']['post']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.POST('/webhooks', { body: data }));
  }

  async update(webhookId: string, data: NonNullable<paths['/webhooks/{id}']['put']['requestBody']>['content']['application/json']) {
    return this.unwrap(this.api.PUT('/webhooks/{id}', { params: { path: { id: webhookId } }, body: data }));
  }

  async del(webhookId: string) {
    return this.unwrap(this.api.DELETE('/webhooks/{id}', { params: { path: { id: webhookId } } }));
  }
}
