import openapiTS, { astToString } from 'openapi-typescript';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const SPEC_URL = 'https://app.heymantle.com/openapi/core-api.json';
const OUTPUT = path.resolve(__dirname, '../src/generated/api.ts');

async function main() {
  console.log('Fetching OpenAPI spec from', SPEC_URL);

  // Fetch and patch the spec to fix any broken $refs
  const response = await fetch(SPEC_URL);
  const spec = await response.json();

  // Patch: FireResponse schema is referenced but not defined
  if (!spec.components.schemas.FireResponse) {
    spec.components.schemas.FireResponse = {
      type: 'object',
      properties: {
        success: { type: 'boolean' },
      },
    };
    console.log('Patched: added missing FireResponse schema');
  }

  const ast = await openapiTS(spec, {
    exportType: true,
    alphabetize: true,
  });
  const output = astToString(ast);
  const header = `// Auto-generated by scripts/generate.ts — DO NOT EDIT\n// Source: ${SPEC_URL}\n// Generated: ${new Date().toISOString()}\n\n`;
  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, header + output);
  console.log(`Written to ${OUTPUT}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
